import React, { useEffect } from 'react'
import './Pad.css'
import Aos from 'aos';
import 'aos/dist/aos.css';

export const Pad = () => {
    useEffect( () => {
Aos.init({ duration: 1000});
    }, [])
    return (
        <div className="holder" data-aos="fade-up">
            <div className="text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis metus dignissim, commodo justo ac, bibendum nunc. Etiam tempus, odio sit amet lacinia lobortis, nisl nibh euismod orci, vel pharetra ipsum sapien quis risus. Aliquam enim diam, imperdiet nec eros sit amet, ultricies ornare ligula. Aenean luctus eros id eros efficitur, a hendrerit mauris rhoncus. Sed a metus at tortor accumsan elementum auctor sed felis. Sed vel felis vulputate, rhoncus diam et, rutrum tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum malesuada malesuada dapibus. Etiam hendrerit nulla quis orci gravida feugiat. Suspendisse potenti. Vestibulum commodo eu mi in sodales. Sed mollis vestibulum nisi. Sed semper ex id libero efficitur, sed mollis sem hendrerit. Nunc vel ante ut purus dictum facilisis. Sed non suscipit diam. Phasellus fringilla velit magna, a auctor diam mollis nec.

Donec consectetur ipsum non velit tincidunt convallis. Quisque ultricies tincidunt aliquam. Quisque rhoncus augue a vulputate convallis. Donec consequat velit quis leo lobortis placerat. Vivamus orci quam, eleifend eu consectetur tempor, congue vel est. Mauris venenatis justo arcu, ac dictum enim sodales vitae. Etiam at elementum augue, eu volutpat felis. Vestibulum mollis auctor ligula, vestibulum dictum neque tincidunt et. Vivamus vitae ullamcorper dui. Cras sit amet interdum dolor, in pharetra dui. Vivamus rhoncus, ante in consequat placerat, sem lacus fringilla quam, nec commodo felis lorem at ex. Curabitur viverra justo eu tellus pretium, eget pellentesque sem iaculis.

Quisque nec elit ac diam consectetur euismod id et diam. Nam vel ante sollicitudin, faucibus lorem vel, hendrerit augue. Maecenas congue sapien sed nulla bibendum pharetra. Sed in commodo mauris. Cras lectus nisl, cursus vitae eleifend ac, auctor et nisi. Vestibulum pulvinar vehicula nulla eu commodo. Ut pharetra iaculis dui quis elementum. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pellentesque aliquam risus. Nunc egestas tempus condimentum. Vestibulum consectetur augue massa, sit amet ullamcorper velit imperdiet ac. Pellentesque in tortor vitae sem molestie viverra ac quis nibh. Sed imperdiet lobortis purus vel vehicula. Praesent gravida, sem id lacinia luctus, mauris leo convallis ligula, ultricies bibendum massa urna ut dui. Donec bibendum, enim non sodales vestibulum, quam massa consequat ante, eu sodales orci mi in quam. Nullam nec nunc quis eros facilisis bibendum. Vestibulum vestibulum, nunc ac consectetur efficitur, eros turpis tincidunt lorem, et porttitor orci dui et quam. Nulla dignissim nunc eros, quis feugiat elit vulputate quis. Donec aliquam luctus efficitur. Quisque lacus eros, placerat id nunc in, tempus malesuada ante. Vestibulum dui ligula, gravida a nulla et, malesuada tristique est.

Nulla vitae feugiat ipsum, a auctor lacus. Suspendisse non ante libero. Sed lacinia porta enim. Donec nisi mi, venenatis ac erat eu, commodo ornare ex. Nam quis risus porta, dictum nulla sed, aliquet leo. Nam pretium purus sit amet porttitor molestie. Nullam ut mi nec nisl rhoncus dignissim. Duis porttitor nulla at rhoncus scelerisque. Mauris sem ligula, malesuada eu nibh cursus, rhoncus euismod magna. Sed nisl diam, commodo non feugiat et, varius nec lorem. Morbi posuere consectetur diam consectetur lobortis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis metus dignissim, commodo justo ac, bibendum nunc. Etiam tempus, odio sit amet lacinia lobortis, nisl nibh euismod orci, vel pharetra ipsum sapien quis risus. Aliquam enim diam, imperdiet nec eros sit amet, ultricies ornare ligula. Aenean luctus eros id eros efficitur, a hendrerit mauris rhoncus. Sed a metus at tortor accumsan elementum auctor sed felis. Sed vel felis vulputate, rhoncus diam et, rutrum tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum malesuada malesuada dapibus. Etiam hendrerit nulla quis orci gravida feugiat. Suspendisse potenti. Vestibulum commodo eu mi in sodales. Sed mollis vestibulum nisi. Sed semper ex id libero efficitur, sed mollis sem hendrerit. Nunc vel ante ut purus dictum facilisis. Sed non suscipit diam. Phasellus fringilla velit magna, a auctor diam mollis nec.

Donec consectetur ipsum non velit tincidunt convallis. Quisque ultricies tincidunt aliquam. Quisque rhoncus augue a vulputate convallis. Donec consequat velit quis leo lobortis placerat. Vivamus orci quam, eleifend eu consectetur tempor, congue vel est. Mauris venenatis justo arcu, ac dictum enim sodales vitae. Etiam at elementum augue, eu volutpat felis. Vestibulum mollis auctor ligula, vestibulum dictum neque tincidunt et. Vivamus vitae ullamcorper dui. Cras sit amet interdum dolor, in pharetra dui. Vivamus rhoncus, ante in consequat placerat, sem lacus fringilla quam, nec commodo felis lorem at ex. Curabitur viverra justo eu tellus pretium, eget pellentesque sem iaculis.

Quisque nec elit ac diam consectetur euismod id et diam. Nam vel ante sollicitudin, faucibus lorem vel, hendrerit augue. Maecenas congue sapien sed nulla bibendum pharetra. Sed in commodo mauris. Cras lectus nisl, cursus vitae eleifend ac, auctor et nisi. Vestibulum pulvinar vehicula nulla eu commodo. Ut pharetra iaculis dui quis elementum. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pellentesque aliquam risus. Nunc egestas tempus condimentum. Vestibulum consectetur augue massa, sit amet ullamcorper velit imperdiet ac. Pellentesque in tortor vitae sem molestie viverra ac quis nibh. Sed imperdiet lobortis purus vel vehicula. Praesent gravida, sem id lacinia luctus, mauris leo convallis ligula, ultricies bibendum massa urna ut dui. Donec bibendum, enim non sodales vestibulum, quam massa consequat ante, eu sodales orci mi in quam. Nullam nec nunc quis eros facilisis bibendum. Vestibulum vestibulum, nunc ac consectetur efficitur, eros turpis tincidunt lorem, et porttitor orci dui et quam. Nulla dignissim nunc eros, quis feugiat elit vulputate quis. Donec aliquam luctus efficitur. Quisque lacus eros, placerat id nunc in, tempus malesuada ante. Vestibulum dui ligula, gravida a nulla et, malesuada tristique est.

Nulla vitae feugiat ipsum, a auctor lacus. Suspendisse non ante libero. Sed lacinia porta enim. Donec nisi mi, venenatis ac erat eu, commodo ornare ex. Nam quis risus porta, dictum nulla sed, aliquet leo. Nam pretium purus sit amet porttitor molestie. Nullam ut mi nec nisl rhoncus dignissim. Duis porttitor nulla at rhoncus scelerisque. Mauris sem ligula, malesuada eu nibh cursus, rhoncus euismod magna. Sed nisl diam, commodo non feugiat et, varius nec lorem. Morbi posuere consectetur diam consectetur lobortis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis metus dignissim, commodo justo ac, bibendum nunc. Etiam tempus, odio sit amet lacinia lobortis, nisl nibh euismod orci, vel pharetra ipsum sapien quis risus. Aliquam enim diam, imperdiet nec eros sit amet, ultricies ornare ligula. Aenean luctus eros id eros efficitur, a hendrerit mauris rhoncus. Sed a metus at tortor accumsan elementum auctor sed felis. Sed vel felis vulputate, rhoncus diam et, rutrum tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum malesuada malesuada dapibus. Etiam hendrerit nulla quis orci gravida feugiat. Suspendisse potenti. Vestibulum commodo eu mi in sodales. Sed mollis vestibulum nisi. Sed semper ex id libero efficitur, sed mollis sem hendrerit. Nunc vel ante ut purus dictum facilisis. Sed non suscipit diam. Phasellus fringilla velit magna, a auctor diam mollis nec.

Donec consectetur ipsum non velit tincidunt convallis. Quisque ultricies tincidunt aliquam. Quisque rhoncus augue a vulputate convallis. Donec consequat velit quis leo lobortis placerat. Vivamus orci quam, eleifend eu consectetur tempor, congue vel est. Mauris venenatis justo arcu, ac dictum enim sodales vitae. Etiam at elementum augue, eu volutpat felis. Vestibulum mollis auctor ligula, vestibulum dictum neque tincidunt et. Vivamus vitae ullamcorper dui. Cras sit amet interdum dolor, in pharetra dui. Vivamus rhoncus, ante in consequat placerat, sem lacus fringilla quam, nec commodo felis lorem at ex. Curabitur viverra justo eu tellus pretium, eget pellentesque sem iaculis.

Quisque nec elit ac diam consectetur euismod id et diam. Nam vel ante sollicitudin, faucibus lorem vel, hendrerit augue. Maecenas congue sapien sed nulla bibendum pharetra. Sed in commodo mauris. Cras lectus nisl, cursus vitae eleifend ac, auctor et nisi. Vestibulum pulvinar vehicula nulla eu commodo. Ut pharetra iaculis dui quis elementum. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pellentesque aliquam risus. Nunc egestas tempus condimentum. Vestibulum consectetur augue massa, sit amet ullamcorper velit imperdiet ac. Pellentesque in tortor vitae sem molestie viverra ac quis nibh. Sed imperdiet lobortis purus vel vehicula. Praesent gravida, sem id lacinia luctus, mauris leo convallis ligula, ultricies bibendum massa urna ut dui. Donec bibendum, enim non sodales vestibulum, quam massa consequat ante, eu sodales orci mi in quam. Nullam nec nunc quis eros facilisis bibendum. Vestibulum vestibulum, nunc ac consectetur efficitur, eros turpis tincidunt lorem, et porttitor orci dui et quam. Nulla dignissim nunc eros, quis feugiat elit vulputate quis. Donec aliquam luctus efficitur. Quisque lacus eros, placerat id nunc in, tempus malesuada ante. Vestibulum dui ligula, gravida a nulla et, malesuada tristique est.

Nulla vitae feugiat ipsum, a auctor lacus. Suspendisse non ante libero. Sed lacinia porta enim. Donec nisi mi, venenatis ac erat eu, commodo ornare ex. Nam quis risus porta, dictum nulla sed, aliquet leo. Nam pretium purus sit amet porttitor molestie. Nullam ut mi nec nisl rhoncus dignissim. Duis porttitor nulla at rhoncus scelerisque. Mauris sem ligula, malesuada eu nibh cursus, rhoncus euismod magna. Sed nisl diam, commodo non feugiat et, varius nec lorem. Morbi posuere consectetur diam consectetur lobortis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis metus dignissim, commodo justo ac, bibendum nunc. Etiam tempus, odio sit amet lacinia lobortis, nisl nibh euismod orci, vel pharetra ipsum sapien quis risus. Aliquam enim diam, imperdiet nec eros sit amet, ultricies ornare ligula. Aenean luctus eros id eros efficitur, a hendrerit mauris rhoncus. Sed a metus at tortor accumsan elementum auctor sed felis. Sed vel felis vulputate, rhoncus diam et, rutrum tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum malesuada malesuada dapibus. Etiam hendrerit nulla quis orci gravida feugiat. Suspendisse potenti. Vestibulum commodo eu mi in sodales. Sed mollis vestibulum nisi. Sed semper ex id libero efficitur, sed mollis sem hendrerit. Nunc vel ante ut purus dictum facilisis. Sed non suscipit diam. Phasellus fringilla velit magna, a auctor diam mollis nec.

Donec consectetur ipsum non velit tincidunt convallis. Quisque ultricies tincidunt aliquam. Quisque rhoncus augue a vulputate convallis. Donec consequat velit quis leo lobortis placerat. Vivamus orci quam, eleifend eu consectetur tempor, congue vel est. Mauris venenatis justo arcu, ac dictum enim sodales vitae. Etiam at elementum augue, eu volutpat felis. Vestibulum mollis auctor ligula, vestibulum dictum neque tincidunt et. Vivamus vitae ullamcorper dui. Cras sit amet interdum dolor, in pharetra dui. Vivamus rhoncus, ante in consequat placerat, sem lacus fringilla quam, nec commodo felis lorem at ex. Curabitur viverra justo eu tellus pretium, eget pellentesque sem iaculis.

Quisque nec elit ac diam consectetur euismod id et diam. Nam vel ante sollicitudin, faucibus lorem vel, hendrerit augue. Maecenas congue sapien sed nulla bibendum pharetra. Sed in commodo mauris. Cras lectus nisl, cursus vitae eleifend ac, auctor et nisi. Vestibulum pulvinar vehicula nulla eu commodo. Ut pharetra iaculis dui quis elementum. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pellentesque aliquam risus. Nunc egestas tempus condimentum. Vestibulum consectetur augue massa, sit amet ullamcorper velit imperdiet ac. Pellentesque in tortor vitae sem molestie viverra ac quis nibh. Sed imperdiet lobortis purus vel vehicula. Praesent gravida, sem id lacinia luctus, mauris leo convallis ligula, ultricies bibendum massa urna ut dui. Donec bibendum, enim non sodales vestibulum, quam massa consequat ante, eu sodales orci mi in quam. Nullam nec nunc quis eros facilisis bibendum. Vestibulum vestibulum, nunc ac consectetur efficitur, eros turpis tincidunt lorem, et porttitor orci dui et quam. Nulla dignissim nunc eros, quis feugiat elit vulputate quis. Donec aliquam luctus efficitur. Quisque lacus eros, placerat id nunc in, tempus malesuada ante. Vestibulum dui ligula, gravida a nulla et, malesuada tristique est.

Nulla vitae feugiat ipsum, a auctor lacus. Suspendisse non ante libero. Sed lacinia porta enim. Donec nisi mi, venenatis ac erat eu, commodo ornare ex. Nam quis risus porta, dictum nulla sed, aliquet leo. Nam pretium purus sit amet porttitor molestie. Nullam ut mi nec nisl rhoncus dignissim. Duis porttitor nulla at rhoncus scelerisque. Mauris sem ligula, malesuada eu nibh cursus, rhoncus euismod magna. Sed nisl diam, commodo non feugiat et, varius nec lorem. Morbi posuere consectetur diam consectetur lobortis.
        </div>
</div>
    )
}
